// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZTvyAuegQvhWKyuMsFoWMeJmjye984Gg',
    appId: '1:495155502870:web:48919123fd0d088f67ba37',
    messagingSenderId: '495155502870',
    projectId: 'fypbin-8a1ae',
    authDomain: 'fypbin-8a1ae.firebaseapp.com',
    databaseURL: 'https://fypbin-8a1ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fypbin-8a1ae.firebasestorage.app',
    measurementId: 'G-6ETKXKCXR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqxoCkh8ly2moyPGsm6yBwiXvLEITw25c',
    appId: '1:495155502870:android:993220713397d8e767ba37',
    messagingSenderId: '495155502870',
    projectId: 'fypbin-8a1ae',
    databaseURL: 'https://fypbin-8a1ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fypbin-8a1ae.firebasestorage.app',
  );
}
